/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Button: typeof import('./src/components/Button.vue')['default']
    Card: typeof import('./src/pages/Home/components/Card.vue')['default']
    Content: typeof import('./src/pages/Home/Content.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    Header: typeof import('./src/pages/Home/Header.vue')['default']
    Home: typeof import('./src/pages/Home/Home.vue')['default']
    InputKit: typeof import('./src/components/InputKit.vue')['default']
    Modal: typeof import('./src/components/Modal.vue')['default']
    Nav: typeof import('./src/pages/Home/Nav.vue')['default']
    NewChat: typeof import('./src/pages/Home/NewChat.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Setting: typeof import('./src/pages/Setting/Setting.vue')['default']
    Switch: typeof import('./src/components/widgets/Switch.vue')['default']
    Tool: typeof import('./src/pages/Home/Tool.vue')['default']
    Upload: typeof import('./src/components/widgets/Upload.vue')['default']
  }
}
