export const OPEN_KEY = 'openKey'
export const OPEN_PROXY = 'openProxy'
export const AZURE_REGION = 'azureRegion'
export const AZURE_KEY = 'azureKey'
export const AZURE_TRANSLATE_KEY = 'azureTranslateKey'
export const VOICE_API_NAME = 'voiceApiName'
export const IS_ALWAYS_RECOGNITION = 'isAlwaysRecognition'
export const OPEN_MODEL = 'openModel'
export const CHAT_API_NAME = 'chatApiName'
export const CHAT_REMEMBER_COUNT = 'chatRememberCount'
export const SELF_AVATAR_URL = 'selfAvatarUrl'
export const OPEN_MAX_TOKEN = 'openMaxToken'
export const TTS_PASSWORD = 'ttsPassword'
export const AUTO_PLAY = 'autoPlay'

